site_name: Guide to Life
theme:
  name: material
nav:
  - Home: README.md
  - Summary: SUMMARY.md
  - Aesthetics & Lifestyle: chapters/01-aesthetics.md
  - Cognitive Domination: chapters/02-cognitive-domination.md
  # - Biohacking: chapters/03-biohacking.md
  # - Strategic Awareness: chapters/04-strategic-awareness.md
  # - Wealth Empire: chapters/05-wealth-empire.md
  # - Physical Mastery: chapters/06-physical-mastery.md
  # - Tactical Survival: chapters/07-tactical-survival.md
  # - Inner Power: chapters/08-inner-power.md
  # - Esoteric Elite: chapters/09-esoteric-elite.md
  # - Appendices: chapters/10-appendices.md
  - Pro Pack: pro.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - assets/custom.css

extra_javascript:
extra_javascript:
  # Plausible main script with all plugins + correct domain
  - https://plausible.io/js/script.file-downloads.hash.outbound-links.pageview-props.revenue.tagged-events.js?domain=liamtjhanley13.github.io/guide-to-life

  # local helper that defines window.plausible()
  - assets/plausible-init.js

