      - name: Install MkDocs, theme, PDF exporter
        run: |
          pip install mkdocs-material mkdocs-pdf-export-plugin

      - name: Build site & export PDFs
        run: |
          mkdocs build --strict
          mkdocs --pdf-export

